### ISSUE TITLE
undefined symbol: PyExc_ImportError

### ISSUE THREAD

**Issue by jtojnar** [eerohele/exalt#16]
Trying Exalt in Sublime 3180 on Ubuntu 18.10, no commands appear in the command palette. The following error appears in the console:

```
reloading plugin Exalt.impl.plugin
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "/home/jtojnar/.config/sublime-text-3/Packages/Exalt/exalt.py", line 84, in plugin_loaded
    sublime_plugin.reload_plugin("%s.impl.plugin" % constants.PLUGIN_NAME)
  File "/opt/sublime_text/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/jtojnar/.config/sublime-text-3/Packages/Exalt/impl/plugin.py", line 28, in <module>
    from lxml import etree
ImportError: /home/jtojnar/.config/sublime-text-3/Packages/lxml/st3_linux_x64/lxml/etree.cpython-33m.so: undefined symbol: PyExc_ImportError
```

**Comment by eerohele** [comment]
Thanks for the report. This is likely an issue with the st3_linux_x64 bit of https://github.com/eerohele/sublime-lxml/.

I don't have a Linux installation handy at the moment, but I'll see whether I can get to the bottom of this with a Vagrant image when I get the chance.
